### ISSUE TITLE
[DO-472] Curate README.md in dos-monorepo

### ISSUE THREAD

**Issue by Etsija** [doubleopen-project/dos#694]
Curation needed in the .ort.yml:

```
curations:
  license_findings:
  - path: "README.md"
    detected_license: "MIT AND LicenseRef-scancode-free-unknown"
    reason: "INCORRECT"
    comment: "Incorrect scanner match."
    concluded_license: "MIT"
```

<sub>From [SyncLinear.com](https://synclinear.com) | [DO-472](https://linear.app/double-open/issue/DO-472/curate-readmemd-in-dos-monorepo)</sub>
